package com.cbfacademy.apiassessment;


import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import java.util.Properties;

@Service
public class Ftse100Service implements Ftse100BasicCrud {

    private List<Ftse100> companies = Ftse100JsonFileReader.readFtse100JsonFile("ftse100.json");

     @Override
    public ResponseEntity<Ftse100> addFtse100Company(Ftse100 newCompany) {
		for (Ftse100 existingCompany : companies){
			if (newCompany.getTickerSymbol().toUpperCase().equals(existingCompany.getTickerSymbol().toUpperCase())){
				return ResponseEntity.status(HttpStatus.ALREADY_REPORTED).body(null); 
				}}
                companies.add(newCompany);
                return ResponseEntity.status(HttpStatus.CREATED).body(newCompany);
                // writing back to my json file with a method here!
                // we want that to persist - need my file to be written back tot ht file!
    }       

    @Override
    public ResponseEntity<List<Ftse100>> getAllFtse100Companies() {
        return ResponseEntity.ok(companies);
    }

    @Override
    public ResponseEntity<Ftse100> getFtse100CompanyByTickerSymbol(String tickerSymbol){
        for (Ftse100 company : companies){
                if (company.getTickerSymbol().toUpperCase().equals(tickerSymbol.toUpperCase())){
                    return ResponseEntity.ok(company);
                }} 
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(null);
    }

    @Override
    public ResponseEntity<Ftse100> updateFtse100Company(String tickerSymbol, Ftse100 updatedCompany) {
        for (Ftse100 company : companies){
                if (company.getTickerSymbol().toUpperCase().equals(tickerSymbol.toUpperCase())){
                    int indexOfCompanyInFtse100List = companies.indexOf(company);
                    companies.set(indexOfCompanyInFtse100List, updatedCompany);
                    return ResponseEntity.ok(updatedCompany);
                }}
                    return ResponseEntity.status(HttpStatus.NOT_FOUND).body(null);   
    }

                    //TICKER SYMBOL, Timestamp, something else and the message: Unable to find Company with Ticker symbol + tickerSymbol. Please try again

    @Override
    public ResponseEntity<List<Ftse100>> deleteFtse100Company(String tickerSymbol) {	
		for (Ftse100 company : companies){
            if (company.getTickerSymbol().toUpperCase().equals(tickerSymbol.toUpperCase())){
				companies.remove(company);
				return ResponseEntity.ok(companies);
				}}
				return ResponseEntity.status(HttpStatus.NOT_FOUND).body(null);		
    }
}

                // exceptions are thrown when conditions havent been met 
                // need to update code below to throw an exception in the format of the 
                // exception class I have created 
                // try to use something that is already working (keep it simple)
                // using what is here already
                // basic exception first then see if and why I want to replace it 
                // make sure I really need it 
                // documentation - write in java doc syntax 
                // presenting a structure of the classes and 
                //interfaces - can be autogenerated (diagram to show program structure)
                // creating class diagrams (Java)
                // any built in functionalities?
                // modelling project - adding a diagram to model it all - class diagram 
//             // exception handling 
// presenting use cases - diagram sshowing the use cases 
// who is doing which action and how which part of my project is acting 
// user does this and makes this request and this happens in response 
// use case diagrams 
//connecting all the pieces with documentation
//             // error handling approriate bodies and status codes 
//             // format json in my local host port if I can
//             // additional requests for my end points 
//             // writing back to my json file also when things are created???
//             // rest template also 
//             // organise the structure of my code 

        

      
